# Automatically merge master into development when changes are pushed to master

name: "master -> development auto-merge"

on:
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  auto-merge:
    permissions: write-all
    name: Merge master into development after a PR is merged
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Temporarily disable branch protection
        uses: ./.github/workflows/branch-protection
        if: always()
        with:
          access_token: ${{ secrets.EDMS_AUTOMERGE_TOKEN }}
          branch: "development"

      - name: merge pre-release
        uses: ./.github/workflows/auto-merge
        id: merge-pre-release
        with:
          github_token: ${{ secrets.EDMS_AUTOMERGE_TOKEN }}
          source: "main"
          target: "Pre-Release"

      - name: merge development
        uses: ./.github/workflows/auto-merge
        id: merge-development
        with:
          github_token: ${{ secrets.EDMS_AUTOMERGE_TOKEN }}
          source: "main"
          target: "development"

      - name: Enable branch protection
        uses: ./.github/workflows/branch-protection
        if: always()
        with:
          access_token: ${{ secrets.EDMS_AUTOMERGE_TOKEN }}
          branch: "development"
