# This is a workflow that updates an Azure Boards work item when a branch is merged

name: "Azure Boards work item state update"

on:
  push:
    branches: 
      - "development" 
      - "AB#**"
  pull_request:
    branches: 
      - "main"
      - "Pre-Release"
    types: 
      - "opened"
      - "closed"
      - "edited"
  pull_request_review:
    types: 
      - "submitted"
      - "edited"
      - "dismissed"

jobs:
  run:
    runs-on: ubuntu-latest
    name: Work item state update workflow
    steps:
      - uses: jlugaro/update-ab-workitem@main
        env:
          ado_token: "${{ secrets.ADO_PAT }}"
          ado_organization: "${{ secrets.ADO_ORGANIZATION }}"
          ado_project: "${{ secrets.ADO_PROJECT }}"
          gh_token: "${{ secrets.GH_PAT }}"
          gh_repo_owner: "edms-devteam-z1"
          gh_repo: "azure-and-github-ci-cd-poc"
          pull_number: "${{github.event.number}}"
          current_branch_name: " ${{github.ref}} "
          dev_branch_name: "development"
          staging_branch_name: "Pre-Release"
          main_branch_name: "main"
          in_progress_state: "Development"
          in_review_state: "In Review"
          merged_state: "Merged"
          staging_state: "Staging"
          closed_state: "Closed"
