# This is a workflow that updates an Azure Boards work item when a branch is merged

name: "Azure Boards work item state update"

on:
  pull_request:
    branches: [main, development]
    types: [opened, closed, edited]
  push:
    branches: [main, development]

jobs:
  alert:
    runs-on: ubuntu-latest
    name: Work item state update workflow
    steps:
      - uses: jlugaro/update-ab-workitem@main
        env:
          ado_token: "${{ secrets.ADO_PAT }}"
          ado_organization: "${{ secrets.ADO_ORGANIZATION }}"
          ado_project: "${{ secrets.ADO_PROJECT }}"
          gh_token: "${{ secrets.GH_PAT }}"
          gh_repo_owner: "edms-devteam-z1"
          gh_repo: "azure-and-github-ci-cd-poc"
          pull_number: "${{github.event.number}}"
          branch_name: " ${{github.ref}} "
          closedstate: "Merged"
          inprogressstate: "Development"
          propenstate: "In Review"
